# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDdd():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ddd(self):
    # Test name: ddd
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://127.0.0.1:8082/")
    # 2 | setWindowSize | 1319x792 | 
    self.driver.set_window_size(1319, 792)
    # 3 | click | id=ss2 | 
    self.driver.find_element(By.ID, "ss2").click()
    # 4 | close |  | 
    self.driver.close()
  
